/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: iSteven (https://sketchfab.com/OneSteven)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/lamborghini-aventador-j-e1123c75f743401e8aacef17abbe31a7
Title: Lamborghini Aventador J
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";

export default function Model(props) {
    const { nodes, materials } = useGLTF("/lamborghini_aventador_j.glb");
    return (
        <RigidBody type="fixed" colliders="trimesh">
            <group {...props} dispose={null}>
                <group
                    position={[-188.848, -58.188, -341.047]}
                    rotation={[-Math.PI / 2, 0, -Math.PI]}
                    scale={2.298}
                >
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.wheel005_Material011_0.geometry}
                        material={materials["Material.011"]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.wheel005_Material010_0.geometry}
                        material={materials["Material.010"]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.wheel005_Material009_0.geometry}
                        material={materials["Material.009"]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.wheel005_Material008_0.geometry}
                        material={materials["Material.008"]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.wheel005_carbon_fiber_0.geometry}
                        material={materials.carbon_fiber}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.wheel005_Material007_0.geometry}
                        material={materials["Material.007"]}
                    />
                </group>
                <group
                    position={[189.886, -58.188, -341.047]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={2.298}
                >
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.wheel003_Material011_0.geometry}
                        material={materials["Material.011"]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.wheel003_Material010_0.geometry}
                        material={materials["Material.010"]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.wheel003_Material009_0.geometry}
                        material={materials["Material.009"]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.wheel003_Material008_0.geometry}
                        material={materials["Material.008"]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.wheel003_carbon_fiber_0.geometry}
                        material={materials.carbon_fiber}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.wheel003_Material007_0.geometry}
                        material={materials["Material.007"]}
                    />
                </group>
                <group
                    position={[183.131, -61.467, 234.981]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={[2.216, 2.187, 2.187]}
                >
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.wheel001_Material011_0.geometry}
                        material={materials["Material.011"]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.wheel001_Material010_0.geometry}
                        material={materials["Material.010"]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.wheel001_Material009_0.geometry}
                        material={materials["Material.009"]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.wheel001_Material008_0.geometry}
                        material={materials["Material.008"]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.wheel001_carbon_fiber_0.geometry}
                        material={materials.carbon_fiber}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.wheel001_Material007_0.geometry}
                        material={materials["Material.007"]}
                    />
                </group>
                <group
                    position={[-182.093, -61.467, 234.981]}
                    rotation={[-Math.PI / 2, 0, -Math.PI]}
                    scale={[2.216, 2.187, 2.187]}
                >
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.wheel002_Material011_0.geometry}
                        material={materials["Material.011"]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.wheel002_Material010_0.geometry}
                        material={materials["Material.010"]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.wheel002_Material009_0.geometry}
                        material={materials["Material.009"]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.wheel002_Material008_0.geometry}
                        material={materials["Material.008"]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.wheel002_carbon_fiber_0.geometry}
                        material={materials.carbon_fiber}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.wheel002_Material007_0.geometry}
                        material={materials["Material.007"]}
                    />
                </group>
                <group position={[0.108, -8.336, -38.463]} scale={73.612}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.object008_carbon_fiber_0.geometry}
                        material={materials.carbon_fiber}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.object008_buttons_0.geometry}
                        material={materials.buttons}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.object008_Material_0.geometry}
                        material={materials.Material}
                    />
                </group>
                <group position={[0.108, 2.242, -143.569]} scale={73.612}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.object016_interior_lod0__s1_0.geometry}
                        material={materials.interior_lod0__s1}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.object016_buttons_0.geometry}
                        material={materials.buttons}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.object016_Material_0.geometry}
                        material={materials.Material}
                    />
                </group>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.object001_leather_0.geometry}
                    material={materials.leather}
                    position={[0.108, -3.381, -26.172]}
                    scale={73.612}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.wheel004_0x10f157_0.geometry}
                    material={materials["0x10f157"]}
                    position={[-189.829, -67.212, -307.457]}
                    rotation={[-1.164, 0, -Math.PI]}
                    scale={2.298}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.wheel000_0x10f157_0.geometry}
                    material={materials["0x10f157"]}
                    position={[190.867, -64.836, -306.907]}
                    rotation={[1.618, 0, 0]}
                    scale={2.298}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.wheel007_0x10f157_0.geometry}
                    material={materials["0x10f157"]}
                    position={[184.077, -56.69, 202.213]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={[2.216, 2.187, 2.187]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.wheel006_0x10f157_0.geometry}
                    material={materials["0x10f157"]}
                    position={[-183.039, -54.406, 202.628]}
                    rotation={[1.93, 0, -Math.PI]}
                    scale={[2.216, 2.187, 2.187]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.object028_Material005_0.geometry}
                    material={materials["Material.005"]}
                    position={[0.138, -9.243, -24.381]}
                    scale={73.612}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.object017_Material002_0.geometry}
                    material={materials["Material.002"]}
                    position={[81.097, 29.674, 107.492]}
                    scale={73.612}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.object007_reverse_light_0.geometry}
                    material={materials.reverse_light}
                    position={[0.108, 35.31, -497.297]}
                    scale={73.612}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.object026_nodamage_lod0__s1_0.geometry}
                    material={materials.nodamage_lod0__s1}
                    position={[81.082, 31.582, 102.098]}
                    scale={73.612}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.object025_M_1_0.geometry}
                    material={materials.material}
                    position={[0.138, -11.61, 36.32]}
                    scale={73.612}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.object023_leather11_0.geometry}
                    material={materials.leather11}
                    position={[0.138, -7.215, 37.811]}
                    scale={73.612}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.object018_Material004_0.geometry}
                    material={materials["Material.004"]}
                    position={[0.138, 40.268, 96.932]}
                    scale={73.612}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.object_Matte__FFCCCCCC1_0.geometry}
                    material={materials.Matte__FFCCCCCC1}
                    position={[0.138, 63.216, -95.748]}
                    scale={73.612}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.object002_black1_0.geometry}
                    material={materials.black1}
                    position={[0.108, -10.464, -57.032]}
                    scale={73.612}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.object003_lights_lod0__spe1_0.geometry}
                    material={materials.lights_lod0__spe1}
                    position={[0.108, 5.592, -48.766]}
                    scale={73.612}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.object004_led__spec_1_0.geometry}
                    material={materials.led__spec_1}
                    position={[0.108, -6.023, 376.998]}
                    scale={73.612}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.object005_nodamage_lod1_0.geometry}
                    material={materials.nodamage_lod1}
                    position={[0.138, 30.351, -198.598]}
                    scale={73.757}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.object006_M_1_0.geometry}
                    material={materials.material}
                    position={[0.108, 34.12, -482.99]}
                    scale={73.612}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.object009_vehiclelights3_0.geometry}
                    material={materials.vehiclelights3}
                    position={[0.108, 37.131, -500.812]}
                    scale={73.612}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.object010_nodamage_lod0__s1_0.geometry}
                    material={materials.nodamage_lod0__s1}
                    position={[0.108, -29.578, -44.356]}
                    scale={73.612}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.object011_Matte__FFCCCCCC_1_0.geometry}
                    material={materials.Matte__FFCCCCCC_1}
                    position={[0.139, 58.433, 118.847]}
                    scale={73.612}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.object012_Material006_0.geometry}
                    material={materials["Material.006"]}
                    position={[0.108, 12.362, -50.522]}
                    scale={73.612}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.object013_Fencing_Mesh_Blue_0.geometry}
                    material={materials.Fencing_Mesh_Blue}
                    position={[0.108, -27.693, -47.736]}
                    scale={73.612}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.object014_nodamage__spec_1_0.geometry}
                    material={materials.nodamage__spec_1}
                    position={[0.108, -63.656, 384.456]}
                    scale={73.612}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.object015_M_1__spec_1_0.geometry}
                    material={materials.M_1__spec_1}
                    position={[0.138, -2.231, 15.124]}
                    scale={73.612}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.object019_vehiclelights2_0.geometry}
                    material={materials.vehiclelights2}
                    position={[0.108, 12.43, -415.01]}
                    scale={73.612}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.object020_lights_lod1_0.geometry}
                    material={materials.lights_lod1}
                    position={[0.108, 34.367, -488.121]}
                    scale={73.612}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.object021_chrome_0.geometry}
                    material={materials.chrome}
                    position={[31.152, -28.384, -243.036]}
                    scale={73.612}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.object022_Material001_0.geometry}
                    material={materials["Material.001"]}
                    position={[0.108, -4.736, 358.379]}
                    scale={73.612}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.dd_engine_0.geometry}
                    material={materials.engine}
                    position={[0.138, 43.922, -334.494]}
                    rotation={[3.113, 0, Math.PI]}
                    scale={192.693}
                />
            </group>
        </RigidBody>
    );
}

useGLTF.preload("/lamborghini_aventador_j.glb");