/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function CharacterModel(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF("/RobotExpressive.glb");

    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Root_Scene" position={[0, -0.9, 0]}>
                <group name="RootNode">
                    <group
                        name="RobotArmature"
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={40}
                    >
                        <primitive object={nodes.Bone} />
                    </group>
                    <group
                        name="HandR"
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={40}
                    >
                        <skinnedMesh
                            name="HandR_1"
                            geometry={nodes.HandR_1.geometry}
                            material={materials.Main}
                            skeleton={nodes.HandR_1.skeleton}
                            castShadow
                        />
                        <skinnedMesh
                            name="HandR_2"
                            geometry={nodes.HandR_2.geometry}
                            material={materials.Grey}
                            skeleton={nodes.HandR_2.skeleton}
                            castShadow
                        />
                    </group>
                    <group
                        name="HandL"
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={40}
                    >
                        <skinnedMesh
                            name="HandL_1"
                            geometry={nodes.HandL_1.geometry}
                            material={materials.Main}
                            skeleton={nodes.HandL_1.skeleton}
                            castShadow
                        />
                        <skinnedMesh
                            name="HandL_2"
                            geometry={nodes.HandL_2.geometry}
                            material={materials.Grey}
                            skeleton={nodes.HandL_2.skeleton}
                            castShadow
                        />
                    </group>
                </group>
            </group>
        </group>
    );
}

useGLTF.preload("/RobotExpressive.glb");