/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ida61xq (https://sketchfab.com/ida61xq)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vr-exhibition-gallery-baked-ee6f3b0d9db14b62a1b3aeef04315313
Title: VR exhibition gallery baked
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";

export default function Model(props) {
    const { nodes, materials } = useGLTF("/vr_exhibition_gallery_baked.glb");

    return (
        <RigidBody type="fixed" colliders="trimesh">
            <group {...props} dispose={null}>
                <group position={[-7.375, 14.197, 5.225]} scale={[3.437, 3.437, 3.443]}>
                    <mesh
                        geometry={nodes.Object_14.geometry}
                        material={materials.Material}
                    />
                    <mesh
                        geometry={nodes.Object_15.geometry}
                        material={materials["light.001"]}
                    />
                </group>
                <mesh
                    geometry={nodes.Object_4.geometry}
                    material={materials["Material.001"]}
                    position={[-7.325, 0.038, 5.19]}
                    scale={3.437}
                    receiveShadow
                />
                <mesh
                    geometry={nodes.Object_6.geometry}
                    material={materials["Material.006"]}
                    position={[-7.325, 6.4, 5.245]}
                    rotation={[0, 0, Math.PI / 2]}
                    scale={1.409}
                />
                <mesh
                    geometry={nodes.Object_8.geometry}
                    material={materials["Material.004"]}
                    position={[-7.305, 6.128, 21.72]}
                    rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                    geometry={nodes.Object_10.geometry}
                    material={materials["Material.003"]}
                    position={[-7.305, 6.128, -21.704]}
                    rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                    geometry={nodes.Object_12.geometry}
                    material={materials["Material.002"]}
                    position={[-7.325, 4.584, -0.413]}
                    scale={7.107}
                />
            </group>
        </RigidBody>
    );
}

useGLTF.preload("/vr_exhibition_gallery_baked.glb");
